Repository jetstack/terraform-google-gke-cluster, pull requests merged in 2019-10, with the labels that each got.

#45 Add script to check required Terraform version
  hack/verify-terraform.sh
  hack/verify.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#49 Update example according to the latest release (v0.1.0)
  example/main.tf
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#48 Fix typos
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#53 Terraform v0.12 support
  README.md
  example/main.tf
  example/variables.tf
  hack/verify.sh
  iam.tf
  main.tf
  variables.tf
Labels: approved, dco-signoff: yes, lgtm, size/L
