Repository jetstack/terraform-google-gke-cluster, pull requests merged in 2019-05, with the labels that each got.

#26 Make verify script change example to use local module when testing
  hack/verify-terraform.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#23 Set Google provider region and project
  .gitignore
  example/main.tf
  iam.tf
  main.tf
Labels: approved, dco-signoff: yes, lgtm, size/M

#27 Defining count inside google_container_node_pool
  main.tf
Labels: approved, dco-signoff: yes, lgtm, size/S
