Repository jetstack/terraform-google-gke-cluster, pull requests merged in 2019-04, with the labels that each got.

#5 Create root OWNERS file
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS

#4 Fix tfvars typo
  example/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#10 Fix provider versions
  example/main.tf
  gke/iam.tf
Labels: approved, dco-signoff: yes, lgtm, size/S

#11 Fail on warnings
  hack/verify-terraform.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#12 Switch to using location argument
  README.md
  example/main.tf
  example/terraform.tfvars.example
  example/variables.tf
  gke/iam.tf
  gke/main.tf
  gke/regional.tf
  gke/variables.tf
  hack/make-zonal.sh
  hack/verify-zonal.sh
  hack/verify.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#14 Restructure module
  example/main.tf
  iam.tf
  main.tf
  variables.tf
Labels: approved, dco-signoff: yes, size/XS

#15 Terraform registry
  README.md
  example/README.md
Labels: approved, dco-signoff: yes, size/S

#20 Move variable description comments to description field
  example/variables.tf
  variables.tf
Labels: approved, dco-signoff: yes, size/L

#18 Update example
  README.md
  example/main.tf
Labels: approved, dco-signoff: yes, size/S
