Repository jetstack/terraform-google-gke-cluster, pull requests merged in 2020-06, with the labels that each got.

#70 Relax provider version contraint
  iam.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#67 Add support for specifying a version for node pools
  main.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#68 Add support for release_channels
  main.tf
  variables.tf
Labels: approved, dco-signoff: yes, lgtm, size/M

#66 Add flag for security groups
  main.tf
  variables.tf
Labels: approved, dco-signoff: yes, lgtm, size/S

#42 Stackdriver logging and monitoring
  README.md
  main.tf
  variables.tf
Labels: approved, dco-signoff: yes, size/M
