Repository jetstack/terraform-google-gke-cluster, pull requests merged in 2020-05, with the labels that each got.

#62 Update example README.md
  example/README.md
Labels: approved, dco-signoff: yes, size/M

#64 Add a min_master_version variable
  main.tf
  variables.tf
Labels: approved, dco-signoff: yes, lgtm, size/S

#65 Relax version requirement for terraform providers
  main.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS
